#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ $# -lt 1 ]; then
  echo "usage: $(basename "$0") <certificate-name>"
  exit 1
fi

certname="$1"

exec security find-certificate -a -c "$certname" -p \
  | keytool -printcert -J-Duser.language=en \
  | grep 'Owner: ' \
  | head -n 1 \
  | sed -n -e 's/^.*OU=\([^:space:,]*\).*$/\1/p'
