#!/bin/sh

# Generate a list of changes between two versions,
# e.g. to generate a changelog for releases.
#
# Usage: script/list-changes [from-revision] [to-revision]
#
# For details on specifying git revisions, check out:
# https://git-scm.com/docs/revisions
#
#
# Examples:
#
#   script/list-changes
#   script/list-changes master
#   script/list-changes v3.0.0
#   script/list-changes v2.0.0 v3.0.0
#

set -o errexit
set -o nounset

cd "$(dirname "$0")/.."

# gets the previous tag
tagversion="$(git describe --abbrev=0 --tags)"

start="${1:-$tagversion}"
end="${2:-HEAD}"

exec git log --no-decorate --pretty='format:- %s (%h)' "${start}..${end}"
