#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPTDIR=$(cd "$(dirname "$0")"; pwd)
# shellcheck source=SCRIPTDIR/lib/utils
source "$SCRIPTDIR/lib/utils"

cd "$(dirname "$0")/.."

./script/check-release-dependencies

branch=$(git branch --show-current)

if [[ "$branch" != "main" ]]; then
  abort "Please only release from the main branch."
fi

yarn checks

version=$(script/version)
tag="v$version"

git tag "$tag"
git push origin "$tag"

# Build artifacts.
yarn bundle:chrome
yarn bundle:firefox

# Create a GitHub release, upload build artifacts.
gh release create "$tag" \
  --generate-notes \
  --verify-tag \
  ./dist/*.zip

gh release download "$tag"\
  --archive=zip \
  --clobber \
  --output="release-artifacts/tickety_tick-${tag##v}.zip"

if has op; then
  apikey=$(op item get "bgi26drb3naqhipfmt5wth6634" --field key)
  apisecret=$(op item get "bgi26drb3naqhipfmt5wth6634" --field secret)
  client_id=$(op item get "yjtvyfa4wcygxlps6smdeybdu4" --field "Client ID")
  client_secret=$(op item get "yjtvyfa4wcygxlps6smdeybdu4" --field "Client Secret")
  refresh_token=$(op item get "yjtvyfa4wcygxlps6smdeybdu4" --field "OAuth Refresh Token")
else
  # Mozilla Add-Ons
  read -rp "Please provide your Mozilla API Key: " apikey
  read -srp "Please provide the corresponding API Secret: " apisecret
  printf "\n\n"

  # Chrome Web Store
  read -rp "Please provide your Chrome Web Store Publish API client ID: " client_id
  read -srp "Please provide your Chrome Web Store Publish API client secret: " client_secret
  printf "\n"
  read -srp "Please provide your Chrome Web Store Publish API refresh token: " refresh_token
  printf "\n\n"
fi

yarn web-ext sign \
  --api-key "$apikey" \
  --api-secret "$apisecret" \
  --source-dir ./dist/firefox \
  --channel=listed \
  --upload-source-code="release-artifacts/tickety_tick-${tag##v}.zip"

printf "\n\n"

gh release upload \
  "$tag" \
  "release-artifacts/tickety_tick-${tag##v}.xpi"

printf "\n\n"

yarn chrome-webstore-upload upload \
  --client-id "$client_id" \
  --client-secret "$client_secret" \
  --refresh-token "$refresh_token" \
  --extension-id "ciakolhgmfijpjbpcofoalfjiladihbg" \
  --auto-publish \
  --source ./dist/chrome.zip

cat <<EOS
Edit the auto-generated release notes on GitHub as necessary:
https://github.com/bitcrowd/tickety-tick/releases/tag/$tag
EOS
