#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname "$0")/.."

CODE_SIGN_IDENTITY="${1:-Apple Development}"
DEVELOPMENT_TEAM=$(script/extract-cert-ou "$CODE_SIGN_IDENTITY")

exec xcodebuild \
  -project safari/tickety-tick.xcodeproj \
  -scheme tickety-tick \
  build \
  CONFIGURATION_BUILD_DIR="$(pwd)/dist/safari" \
  CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
  DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"
